### PR TITLE
Add some proc/sys linux artifacts

### PR DESCRIPTION
**Pull request by destijl**

### CODE REVIEW

**Comment by destijl** [comment]
@joachimmetz

**Comment by destijl** [comment]
The best distinction I can make as to why these particular bits of proc, is that they are all security relevant.  To be more specific we'd need to break them all up individually, maybe that makes more sense....

**Comment by sebastianwelsh** [comment]
See pull/27 for an updated set of proc entries with a more specific breakdown.

**Comment by joachimmetz** [comment]
I'll have a look later today.

**Comment by destijl** [comment]
closing this in favour of sebastian's version.

**Pull request closed without merging**
