### PR TITLE
Changes for artifact definition naming conventions #25

### PR DESCRIPTION
**Pull request by joachimmetz**
This change is [Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/194)

### CODE REVIEW

**Comment by joachimmetz** [comment]
@destijl there is more to be cleaned up but if you can have a look at the initial changes to see if you agree with the direction in which it is heading.

**Comment by destijl** [comment]
I don't think this is worth it. OSX prefix is fine, since they look to all have it, we should just leave it. Renaming is disruptive, there's probably artifacts grr depends on that will have to get added to legacy.

**Comment by joachimmetz** [comment]
What about the other style notes?

**Comment by destijl** [comment]
Sorry, didn't read that far down :) The doc changes LGTM.

**Comment by joachimmetz** [comment]
Made a copy of artifact definition names hardcoded in GRR (https://github.com/google/grr/blob/master/grr/config/artifacts.py) into legacy

**Pull request merged**
