### PR TITLE
Add transaction log files to the registry artifact

### PR DESCRIPTION
**Pull request by Karneades**
For completeness in collecting registry files, also the  transaction log files (LOG,LOG1,LOG2) must be collected. 

See [registry file spec](https://github.com/msuhanov/regf/blob/master/Windows%20registry%20file%20format%20specification.md)
> transaction log files are used to perform fault-tolerant writes to primary files. Before writing modified (dirty) data to a primary file, a hive writer will store this data in a transaction log file. If an error (like a system crash) occurs when writing to a transaction log file, a primary file will remain consistent; if an error occurs when writing to a primary file, a transaction log file will contain enough data to recover a primary file and bring it back to the consistent state.

More information about [transaction log file format is also found in the spec](https://github.com/msuhanov/regf/blob/master/Windows%20registry%20file%20format%20specification.md#format-of-transaction-log-files).

For example the Registry Explorer is able to integrate these changes when loading the registry files (https://binaryforay.blogspot.ch/2018/03/updates-to-left-of-me-updates-to-right.html).

### CODE REVIEW

**Comment by joachimmetz** [comment]
> For completeness in collecting registry files, also the transaction log files (LOG,LOG1,LOG2) must be collected.

I don't understand this claim. How does this add to completeness? You're not including [transactional Registry (TxR)](https://github.com/msuhanov/regf/blob/master/Windows%20registry%20file%20format%20specification.md#transactional-registry-txr)? Also completeness relative to what? I recommend to refrain from making these speculative claims. I can imaging several scenarios where the transaction log files do not add value for the case at hand.

Regarding the proposed changes please put these in separate artifacts e.g. WindowsSystemRegistryTransactionLogFiles

**Comment by Karneades** [comment]
Before writing modified (dirty) data to a primary file, a hive writer will store this data in a transaction log file. If an error (like a system crash) occurs when writing to a transaction log file, a primary file will remain consistent; if an error occurs when writing to a primary file, a transaction log file will contain enough data to recover a primary file and bring it back to the consistent state.

**Comment by joachimmetz** [comment]
> Wouldn't it be wise to collect them every time we collect the primary files? If they're not needed, fine, but if we need them, we have the files in place.

that is up to you as an analyst, artifacts definitions are no replacement from doing proper analysis they are there to not have to remember everything in detail

> From the initial post:

yes I understand the purpose of transaction logs; my comment is not providing speculative remarks, especially about completeness of analysis, there are a lot of folks that read such comments and assume this is ground truth instead of evaluating nuances

> WindowsSystemRegistryPrimaryFiles

Please keep WindowsSystemRegistryFiles as-is if you want an artifact group for easy usage maybe create WindowsSystemRegistryFilesAndTransactionLogs that contains WindowsSystemRegistryFiles and WindowsSystemRegistryTransactionLogFiles

**Comment by Karneades** [comment]
> Please keep WindowsSystemRegistryFiles as-is if you want an artifact group for easy usage maybe create WindowsSystemRegistryFilesAndTransactionLogs that contains WindowsSystemRegistryFiles and WindowsSystemRegistryTransactionLogFiles

Add dedicated artifacts for transaction logs and add artifact groups for easier usage for the registry artifacts.

**Comment by joachimmetz** [comment]
thx, I'll have a more detailed look at the changes later today

**Comment by joachimmetz** [comment]
I've remove some of the description text seeing this was copied from https://github.com/msuhanov/regf/blob/master/Windows%20registry%20file%20format%20specification.md without the proper attribution. Seeing the work is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

**Comment by joachimmetz** [comment]
LGTM, merged

**Comment by Karneades** [comment]
Thanks for the exact review! My bad... sorry for that!

Thanks for the merge.

AN Do., Mai 3, 2018 bei 21:00, Joachim Metz <notifications@github.com> Schrieb:

> I've remove some of the description text seeing this was copied from https://github.com/msuhanov/regf/blob/master/Windows%20registry%20file%20format%20specification.md without the proper attribution. Seeing the work is licensed under the [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/).

**Pull request merged**
