### PR TITLE
Added PowerShell Logs

### PR DESCRIPTION
**Pull request by ewalshmndt**

### CODE REVIEW

**Comment by joachimmetz** [comment]
@ewalshmndt thanks for the proposed changes

**Comment by ewalshmndt** [comment]
They can be combined

**Comment by joachimmetz** [comment]
Informational renamed it to WindowsXMLEventLogPowerShell to match other XML event log artifact definition naming convention.

**Review by joachimmetz — APPROVED** [review]
LGTM

**Pull request merged**
