### PR TITLE
Fix minor lint issues, remove unnecessary kwargs

### PR DESCRIPTION
**Pull request by destijl**
The kwargs used by subclasses was weird.  If they were ever set we just raised, so having it seems pretty pointless.

@joachimmetz

### CODE REVIEW

**Comment by destijl** [comment]
OK, I'll rethink this.

**Comment by destijl** [comment]
As is, you essentially modify the API to allow for failure then check for the failure.  But this is unnecessary. since the classes already define what arguments they can accept.  I added a test to demonstrate. PTAL.

**Comment by joachimmetz** [comment]
If not needed I'm fine with getting rid of it.

**Comment by destijl** [comment]
OK, merging now.

**Pull request merged**
