### PR TITLE
 Added validator check for Mac OS private paths #309

### PR DESCRIPTION
**Pull request by joachimmetz**

### CODE REVIEW

**Comment by joachimmetz** [comment]
@pstirparo could you spot check this PR and see if this is inline with our conversation.

**Comment by cugu** [comment]
Sorry for the interference, but what about 

``` yml
- type: FILE
  attributes: {paths: ['/private/etc/ssh/sshd_config']}
  supported_os: [Darwin]
- type: FILE
  attributes: {paths: ['/etc/ssh/sshd_config']}
  supported_os: [Darwin,Linux]
```

instead of

``` yml
- type: FILE
  attributes:
    paths:
    - '/etc/ssh/sshd_config'
    - '/private/etc/ssh/sshd_config'
  supported_os: [Darwin]
- type: FILE
  attributes: {paths: ['/etc/ssh/sshd_config']}
  supported_os: [Linux]
```

**Comment by joachimmetz** [comment]
> Sorry for the interference, but what about

Interesting idea but IMHO a couple of downsides of that approach:

* slightly more complex conditional logic is necessary to validate
* easy to overlook the second source as one that applied to Darwin

For now I opt to keep it as is, and revisit this idea when I address the `supported_os` https://github.com/ForensicArtifacts/artifacts/issues/274

**Comment by cugu** [comment]
Validation of duplicate paths #41 is more complicated this way.

**Comment by joachimmetz** [comment]
> Validation of duplicate paths #41 is more complicated this way.

could you explain/elaborate why you think this is the case?

**Comment by cugu** [comment]
With the current solution there are duplicates of file paths when ignoring the supported os. My solution prevents duplicate file paths.

**Comment by joachimmetz** [comment]
> My solution prevents duplicate file paths.

How? I'm missing the necessary context.

Your suggested approach reduces the **need** for duplication in a single artifact definition/
However duplication can still exist across artifact definitions, which is what hinted at in #41.

**Comment by cugu** [comment]
A simple validator for duplicate file paths will find the duplicate `/etc/ssh/sshd_config` in 

``` yaml
- type: FILE
  attributes:
    paths:
    - '/etc/ssh/sshd_config'
    - '/private/etc/ssh/sshd_config'
  supported_os: [Darwin]
- type: FILE
  attributes: {paths: ['/etc/ssh/sshd_config']}
  supported_os: [Linux]
```

but not in 
```yaml
- type: FILE
  attributes:
    paths:
    - '/etc/ssh/sshd_config'
    - '/private/etc/ssh/sshd_config'
  supported_os: [Darwin]
- type: FILE
  attributes: {paths: ['/etc/ssh/sshd_config']}
  supported_os: [Linux]
```

Anyway it does not matter to much, I just have to make my duplication checker aware of different supported_os.

**Comment by joachimmetz** [comment]
> Anyway it does not matter to much, I just have to make my duplication checker aware of different supported_os.

Note that supported_os is on the list to be changed, I opt not to invest too much effort here yet.

**Pull request merged**
