### PR TITLE
Added messaging and email client artifacts

### PR DESCRIPTION
**Pull request by sydp**
Added additional Linux based artifacts:
* Thunderbird
* Evolution
* Signal Desktop

### CODE REVIEW

**Comment by joachimmetz** [comment]
Please fix lint error https://github.com/ForensicArtifacts/artifacts/runs/7462700048?check_suite_focus=true#step:7:25

**Review by joachimmetz — CHANGES_REQUESTED** [review]
Linter CI tests fails

**Comment by sydp** [comment]
> Linter CI tests fails

Fixed.  Thanks.

**Review by joachimmetz — APPROVED** [review]
LGTM

**Pull request merged**
