### PR TITLE
Add WinRAR AV and Viewer keys

### PR DESCRIPTION
**Pull request by Onager**
[Review on Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/56)

### CODE REVIEW

**Comment by joachimmetz** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions, all commit checks successful.

---

<sup>**[definitions/windows.yaml, line 611 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56#-JpcDuvVsXpTfxBiCEaw)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/ac65f4b77ea053f6fe5683de8334397c275cc3c8/definitions/windows.yaml#L611)):</sup>
style guide says to make this 1 line
https://github.com/ForensicArtifacts/artifacts/blob/master/docs/Artifacts%20definition%20format%20and%20style%20guide.asciidoc#4-sources (see: Style note:)

---

<sup>**[definitions/windows.yaml, line 614 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56#-JpcDhcnj4M56-4nBBiP)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/ac65f4b77ea053f6fe5683de8334397c275cc3c8/definitions/windows.yaml#L614)):</sup>
use:
urls:
- url
- url

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56)

**Comment by Onager** [comment]
Review status: 0 of 1 files reviewed, 2 unresolved discussions, some commit checks pending.

---

<sup>**[definitions/windows.yaml, line 611 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56#-JpcDuvVsXpTfxBiCEaw)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/ac65f4b77ea053f6fe5683de8334397c275cc3c8/definitions/windows.yaml#L611)):</sup>
Done.

---

<sup>**[definitions/windows.yaml, line 614 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56#-JpcDhcnj4M56-4nBBiP)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/ac65f4b77ea053f6fe5683de8334397c275cc3c8/definitions/windows.yaml#L614)):</sup>
Done.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56)

**Comment by joachimmetz** [comment]
LGTM, will merge when Travis completes.

---

Review status: 0 of 1 files reviewed, 2 unresolved discussions, some commit checks pending.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56)

**Comment by joachimmetz** [comment]
Review status: all files reviewed, all discussions resolved, some commit checks pending.
Reviewed files:
- definitions/windows.yaml @ r2

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/56)

**Pull request merged**
