### PR TITLE
Add SSH Host Key artifact

### PR DESCRIPTION
**Pull request by Plantain**
Add an artifact to collect SSH host keys from /etc/ssh/ssh_host_*_key.pub.

[Review on Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/127)

### CODE REVIEW

**Comment by destijl** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---

<sup>**[definitions/linux.yaml, line 427 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/127#-K2TCFPxwD2gaj8DbhAM)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/b53974c51958ae9aec3ca808f7b5309b74175be5/definitions/linux.yaml#L427)):</sup>
SSHHostPublicKeys

Put the artifact in alphabetical order with the others.


---

<sup>**[definitions/linux.yaml, line 428 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/127#-K2TCIRSNz6nYJ_jFtCZ)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/b53974c51958ae9aec3ca808f7b5309b74175be5/definitions/linux.yaml#L428)):</sup>
Just `SSH host public keys.` The artifacts don't collect anything and linux is implied.


---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/127)

**Comment by destijl** [comment]
Ping, just some minor changes and this can go in.

**Comment by destijl** [comment]
Friendly ping.

**Comment by Plantain** [comment]
Sorry, been on / am on leave, will get to this soon.

**Comment by Plantain** [comment]
I have made the requested changes.

**Comment by destijl** [comment]
Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/127)*

**Comment by destijl** [comment]
Thanks!

**Pull request merged**
