### PR TITLE
Change type from PATH to FILE

### PR DESCRIPTION
**Pull request by rgayon**

### CODE REVIEW

**Comment by aarontp** [comment]
OMG, yes.  I just spent a couple hours looking through Plaso / DFVFS / ForensicArtifacts to see how to get  image_export.py to support PATH types for this artifact, and I was just coming here to find the original pull request for the Hadoop artifact to see if there were any comments about why this might need to be a PATH instead of a FILE and I happened to run across this.

@rgayon is this ready for review?  Is there any reason why this wouldn't work?

**Comment by rgayon** [comment]
I chatted a bit with @joachimmetz and this should definitely work. I can't really remember why I chose PATH and not FILE. I think I thought I needed PATH to have the paths expansions with the *, but it most likely is a mistake from my side.

And yes, requesting review right now

**Comment by aarontp** [comment]
Awesome!  Thanks so much!!

I hate to ask, but is there any chance of a release coming any time soon? :)

**Comment by joachimmetz** [comment]
@aarontp a new version has been released

**Comment by aarontp** [comment]
Double awesome, thanks!!  Have a great weekend, :)

**Pull request merged**
