### PR TITLE
Added Windows COM Registry keys.

### PR DESCRIPTION
**Pull request by joachimmetz**
[Review on Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/141)

### CODE REVIEW

**Comment by destijl** [comment]
Looks like these might be missing CLSIDs...As discussed the empty value won't work in GRR.

**Comment by joachimmetz** [comment]
I've added a * for the actual ids

**Comment by destijl** [comment]
LGTM. I thought default value support for GRR was in, but it doesn't look like it and I couldn't find the change. Don't submit this until that's done.

**Comment by destijl** [comment]
The default value support is in now:
https://github.com/google/grr/blob/master/lib/flows/general/collectors.py#L341

**Pull request merged**
