### PR TITLE
Adjusted typo of CurrentControlSet

### PR DESCRIPTION
**Pull request by marcurdy**
Small change.

### CODE REVIEW

**Comment by joachimmetz** [comment]
Thx, for the corrections

**Comment by marcurdy** [comment]
YW. I've created a script to use your yamls as input and create plaso tag
files.

**Comment by joachimmetz** [comment]
Ack, know that plaso directly supports artifacts as collection filters as well

**Comment by marcurdy** [comment]
I only learned this 20 minutes ago. Thank you for your huge contributions!

One question on the windows yaml.
WindowsCOMLocalServers contains different description styles. One places
the LocalServer as a value. The second puts it alongside the key and leaves
the value empty. Is this intentional?

            "key": "HKEY_LOCAL_MACHINE\\Software\\Classes\\CLSID\\*",
            "value": "LocalServer"
          }, {
            "key":
"HKEY_LOCAL_MACHINE\\Software\\Classes\\CLSID\\*\\LocalServer32",
            "value": ""

WindowsCOMInprocServers puts all values in the key leaving value along.

Cheers

**Comment by joachimmetz** [comment]
The first means key with value LocalServer, the second means default value of key. I'll double check but the second could be an error. For GRR historically this does not make a difference because the value is appended to the key path (which can cause issues with e.g. bagmru paths where subkey and value names are the same).

**Pull request merged**
