### PR TITLE
Add more Jupyter notebook configuration file paths.

### PR DESCRIPTION
**Pull request by hacktobeer**
Added more Jupyter configuration file paths using the below source.
https://docs.jupyter.org/en/latest/use/jupyter-directories.html#configuration-files

### CODE REVIEW

**Comment by hacktobeer** [comment]
@joachimmetz could you do a review whenever time permits?

**Review by joachimmetz — APPROVED** [review]
LGTM

**Comment by hacktobeer** [comment]
Thanks for the cleanup. I see one codecov test failing, don't know if relevant....

**Comment by joachimmetz** [comment]
> Thanks for the cleanup. I see one codecov test failing, don't know if relevant....

That's fine, it just indicates that the patch reduced the overall test coverage stats

**Pull request merged**
