### PR TITLE
PEP8 fixes

### PR DESCRIPTION
**Pull request by 2xyo**
This pull request aims to resolve all PEP8 violations

[Review on Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/51)

### CODE REVIEW

**Comment by destijl** [comment]
AFAICT this is just 2 to 4 space indentation? Google style is 2 spaces (and I personally prefer it), so I'd like to keep this repo using 2.  Apologies if this makes your linter angry, it makes mine happy :)

**Comment by 2xyo** [comment]
Where is the official Google pep8/pytlint config?

**Comment by destijl** [comment]
The style guide is here (sort of):
http://google-styleguide.googlecode.com/svn/trunk/pyguide.html

The two key differences between that public version and internal style are 2 spaces, and CamelCase functions.  Plaso has a list here:
https://github.com/log2timeline/plaso/wiki/Style-guide

I'd be OK with converting to PEP8 function_names since this is a standalone opensource python project and the CamelCase convention was for internal reasons, but I'd like to keep 2 spaces.

**Comment by joachimmetz** [comment]
I opt to keep the camel case, so you can easily see the difference between the code of the module and non-module code.

**Comment by joachimmetz** [comment]
I don't agree with these style changes, they do not make the code more readable.

**Comment by joachimmetz** [comment]
Discussed it with @destijl, most of the code already uses the plaso style which uses the 2 spaces indentation not the 4. The PEP8 violations are largely due to the 79 char rule. The other aspects of the PEP8 IMO do not add much value in additional readability improvements. Hence I opt not to move forward with this CL. 

> Where is the official Google pep8/pytlint config?

I was using the plaso pylintrc I can add it to the project if you want. Here we recently switched to pylint 1.4.0 which finds some more issues than its predecessors.

**Comment by destijl** [comment]
Lets close this one, joachim is adding a linter script in another PR.

**Pull request closed without merging**
