### PR TITLE
Moved tests to separate directory.

### PR DESCRIPTION
**Pull request by joachimmetz**
[Review on Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/72)

### CODE REVIEW

**Comment by destijl** [comment]
LGTM

---

Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/source_type.py, line 10 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/72#-Js7EH4qLE1A9Ejwq2Bb)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/a2f7948acbbc19418082ae716e8a3d62202878e5/tests/source_type.py#L10)):</sup>
nwhy?

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/72)

**Comment by joachimmetz** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/source_type.py, line 10 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/72#-Js7EH4qLE1A9Ejwq2Bb)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/a2f7948acbbc19418082ae716e8a3d62202878e5/tests/source_type.py#L10)):</sup>
We are testing for bogus kwargs, pylint complains about that ;)

I also need to add a small fix for the tests in tools.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/72)

**Comment by destijl** [comment]
Review status: 0 of 10 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---

<sup>**[tests/source_type.py, line 10 \[r1\]](https://reviewable.io:443/reviews/forensicartifacts/artifacts/72#-Js7EH4qLE1A9Ejwq2Bb)** ([raw file](https://github.com/forensicartifacts/artifacts/blob/a2f7948acbbc19418082ae716e8a3d62202878e5/tests/source_type.py#L10)):</sup>
Those tests should be removed and are a hangover from the old code. Testing that a function rejects parameters with wrong keywords isn't something we need to do.

---


Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/72)

**Comment by joachimmetz** [comment]
I'll clean that up then and add a fix for the missing validation tests.

**Comment by destijl** [comment]
LGTM

---

Review status: 0 of 17 files reviewed at latest revision, 1 unresolved discussion, all commit checks successful.

---



Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/forensicartifacts/artifacts/72)

**Pull request merged**
