### PR TITLE
Renamed ARTIFACT to ARTIFACT_GROUP #139

### PR DESCRIPTION
**Pull request by joachimmetz**
Changes for: https://github.com/ForensicArtifacts/artifacts/issues/139

[Review on Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/143)

### CODE REVIEW

**Comment by destijl** [comment]
This LGTM but we need to make changes on the GRR side too. And we probably want to support both for a while, and warn people to change over their artifacts, so it might be a while before we submit this.

**Comment by destijl** [comment]
GRR support is in for ARTIFACT_GROUP so this can go in after you merge.

**Comment by joachimmetz** [comment]
Ack, I'll add a small documentation update to the CL as well.

**Comment by joachimmetz** [comment]
Merged with upstream master, will merge PR once tests complete.

**Pull request merged**
