### PR TITLE
Added more Windows Artifacts

### PR DESCRIPTION
**Pull request by pidydx**
[Review on Reviewable](https://reviewable.io/reviews/forensicartifacts/artifacts/33)

### CODE REVIEW

**Comment by destijl** [comment]
Awesome, thanks! It would be really nice to have some documentation links though.

**Comment by pidydx** [comment]
I have been trying to figure out the best way to handle that.  I might just dig up some MSDN links for things until I can come up with something better.

**Comment by joachimmetz** [comment]
An alternative is adding documentation to forensicswiki.org

**Comment by joachimmetz** [comment]
@pidydx can you make sure to mark Registry values different from Registry keys, I know the format currently does not support it but it makes life easier when it does

**Comment by pidydx** [comment]
Re: Documentation:  I do have a forensicswiki.org account now, but I want to make sure I can find "official" documentation on the details of how some of the keys work so I don't wind up documenting screwed up descriptions of the persistence mechanisms or expected values.  My longer term plan is to sort all these things by loose categories of why someone would care about each one.  (Persistence, Escalation, History/Forensics, etc)

Re: Key/Value.  Do you mean to mark them by which ones are returning a single specific Value vs the ones that are going to return a set of Keys and values?

**Comment by joachimmetz** [comment]
> I want to make sure I can find "official" documentation on the details of how some of the keys work so I don't wind up documenting screwed up descriptions of the persistence mechanisms or expected values. 

I've notices that sometimes this means piecing together various MSDN sources. Also a wiki article could give more room for actually describing Persistence, Escalation, History/Forensics, etc.

> Key/Value. Do you mean to mark them by which ones are returning a single specific Value vs the ones that are going to return a set of Keys and values?

In https://github.com/ForensicArtifacts/artifacts/pull/11 I'm separating Registry keys from values (since the current variant does not support this). If you can indicate in the doc string if its a key or value that could be useful when merging these with the pull request.

**Comment by pidydx** [comment]
>I've notices that sometimes this means piecing together various MSDN sources. Also a wiki article could give more room for actually describing Persistence, Escalation, History/Forensics, etc.

The biggest headache I have run into is which HKU keys can override HKLM ones so I have a lot of artifacts that just attempt to grab both just to be sure.  My plan is to dig through MSDN, Windows Internals, and threat research blog stuff to try and put something reasonable together after I get done brain dumping all of my notes into artifacts.  Unfortunately most of my notes are "You care about this key" and less "and this is why".

>In #11 I'm separating Registry keys from values (since the current variant does not support this). If you can indicate in the doc string if its a key or value that could be useful when merging these with the pull request.

Ah, I see how you mean.  Should I just document or do you want me to change to the new format?

**Comment by joachimmetz** [comment]
> Ah, I see how you mean. Should I just document or do you want me to change to the new format?

Since it is not yet part of HEAD I opt to just document, otherwise you'll have to wait for the change to be submitted before we can integrate any of your changes in the mean time.

**Comment by joachimmetz** [comment]
> My plan is to dig through MSDN, Windows Internals, and threat research blog stuff to try and put something reasonable together after I get done brain dumping all of my notes into artifacts.

For reference URL I personally would go for forensicswiki (otherwise a github wiki if you want more control over it?), the advantage being that other can help you out writing. Side note: I'm personally not a fan of using blogs for reference material.

**Comment by pidydx** [comment]
I just need to find the time to sit down and write up the forensic wiki stuff.  I don't generally trust blogs to stay online anyways, but I have a few links that can at least be temporary documentation of why a particular artifact is interesting.

**Comment by joachimmetz** [comment]
That would be great, thanks in advance.

**Comment by pidydx** [comment]
I added a few more and put comments in place for REGISTRY_VALUE vs REGISTRY_KEY.  I really like the idea of removing ambiguity like this as it has been a pain to get definitive answers on what some of the optional entries really are.  I can correct any I mislabeled when I can test more of them against the fleet.

**Comment by joachimmetz** [comment]
>  I really like the idea of removing ambiguity like this as it has been a pain to get definitive answers on what some of the optional entries really are.

It also necessary since technically a value can:

* have the same name as a subkey e.g. BagMRU
* contain the Registry path separator `\` as a valid character

**Comment by destijl** [comment]
we're pretty close to getting the format change PR in, I think you should wait on this one and just move to the new format since you have a bunch of reg key values that would benefit.

**Comment by pidydx** [comment]
I was afraid of that.  Converting this unmerged mess is going to be a pain. :) I will try to get this cleaned up soon.

**Comment by joachimmetz** [comment]
Not sure why you closed this. @pidydx should otherwise Greg or my try to merge these in?

**Comment by pidydx** [comment]
Yes, this one was using the old format so rather than dealing with a crazy merge mess I just pulled the latest and rebuilt using the new format.

**Comment by joachimmetz** [comment]
Great, was missing that context, I'll have a look at the new PR.

**Pull request closed without merging**
