### PR TITLE
Add definition for Siemens WinCC logs

### PR DESCRIPTION
**Pull request by meeehow**
This PR creates new ics.yaml file and adds definition for Siemens WinCC software logs.

### CODE REVIEW

**Comment by joachimmetz** [comment]
@meeehow FYI validation test is failing

```
======================================================================
FAIL: testArtifactDefinitionsValidator (validator_test.ArtifactDefinitionsValidatorTest)
Runs the validator over all the YAML artifact definitions files.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\projects\artifacts\tests\validator_test.py", line 24, in testArtifactDefinitionsValidator
    self.assertTrue(
AssertionError: False is not true : in definitions file: data\ics.yaml
----------------------------------------------------------------------
```

**Comment by meeehow** [comment]
```
testArtifactDefinitionsValidator (validator_test.ArtifactDefinitionsValidatorTest)
Runs the validator over all the YAML artifact definitions files. ... WARNING:root:Artifact definition: WindowsSiemensWinCCLogFile in file: data/ics.yaml contains Windows path that contains an unuspported environment variable: "%%environ_programdata%%".
WARNING:root:Artifact definition: WindowsSiemensWinCCLogFile in file: data/ics.yaml contains Windows path that contains an unuspported environment variable: "%%environ_programdata%%".
WARNING:root:Artifact definition: WindowsSiemensWinCCLogFile in file: data/ics.yaml contains Windows path that contains an unuspported environment variable: "%%environ_programdata%%".
FAIL
```

testArtifactDefinitionsValidator is complaining about the %%environ_programdata%% variable, if I delete the lines containing it the tests pass.

**Comment by joachimmetz** [comment]
Use `%%environ_allusersappdata%%` for now this is the pre-Window Vista naming convention and there is an issue pending to change this https://github.com/ForensicArtifacts/artifacts/issues/339

**Review by joachimmetz — COMMENTED** [review]
LGTM

**Pull request merged**
