### PR TITLE
Updated Prefetch to gather prefetch files generated by binaries executed...

### PR DESCRIPTION
**Pull request by pidydx**
... from ADS

### CODE REVIEW

**Comment by joachimmetz** [comment]
This change makes the definitions too large.

What additional files do you think need to be added to the Prefetch files definition?

If you mean the *.db files those are likely [SuperFetch databases](https://github.com/libyal/libagdb/blob/master/documentation/Windows%20SuperFetch%20(DB)%20format.asciidoc) files not Prefetch files.

**Comment by pidydx** [comment]
If I attach evil.exe as an ADS c:\windows\system32\notepad.exe:evil.exe then the resulting file will be ..\Prefetch\notepad.exe:evil.pf.  The same is true for directories.  It will create a file/directory for whatever the ADS was attached to and then create the .pf file as an ADS on that file/directory.

**Comment by joachimmetz** [comment]
Yes but that would mean the glob *.pf applies as well. Not sure why you want to turn it into a * instead?

**Comment by pidydx** [comment]
What would be the best way to define that in this artifact?

**Comment by joachimmetz** [comment]
Let me sync with Greg and see if we can come up with a good solution. I'm leaning towards adding path with data stream/fork name or equiv.

**Comment by joachimmetz** [comment]
I've created https://github.com/ForensicArtifacts/artifacts/issues/13 to track the status of this.

**Comment by joachimmetz** [comment]
I'll will change the path definition to provide for a data stream name glob. The GRR implementation will initially not support this, but we'll work to get that support in.

Regarding this pull request, you should be able to create a custom artifact in GRR e.g. "PrefetchDirectory" as a work around.

**Pull request closed without merging**
