### PR TITLE
Adding Kubernetes artifacts

### PR DESCRIPTION
**Pull request by pr3l14t0r**
Heyho together! 
I am currently finalizing my master thesis about `Kubernetes Forensics` where one objection is the identification and description of forensic artifacts related to Kubernetes.
To identify them, I have used a method of automated differential analysis between two states, mainly working with `Pod` resources. That allows to trace changes on a nodes file system level so that characteristic file changes can be identified and analyzed. 

To bring my results into a usable and understandable format I have chosen to follow your formatting guidelines so that the results can get contributed to the repo. 

I hope that I understood the guidelines correctly and did not mess up completely ... :D 

To mark the purpose/ type of a placeholder in paths i have decided to use the following style:

`attributes: {paths: ['/var/log/pods/<namespace>_<pod_name>_<pod_id>/<container_name>/<num>.log']}`

If `%%` signs should be used instead I can just exchange the characters. 

Looking forward for your feedback! :)

Kind regards,
Christoph

### CODE REVIEW

**Comment by joachimmetz** [comment]
I'll have a run when time permits, CI tests are currently failing on `artifacts.errors.FormatError: Artifact definition: KubernetesLogs found undefined labels: Log.`

**Comment by joachimmetz** [comment]
Changed the docstrings to match the style guide:

```
'/var/log/pods/<namespace>_<pod_name>_<pod_id>/<container_name>/<num>.log'
```

Is not going to work, you'll need to make this a glob or add supported place holders

**Comment by pr3l14t0r** [comment]
Ahoi again! 
Sorry for my confusion here. 

I've exchanged the paths now with values that match the glob pattern and added an additionaly explanation to the respective `docs` to explain how the path is structured.

I've also ran the `run_tests.py` locally and it says `OK`. :) 

Regards,
Christoph

**Comment by joachimmetz** [comment]
@pr3l14t0r thx for the proposed changes, I'll have a more detailed look later (when time is more favorable)

**Review by joachimmetz — COMMENTED** [review]
LGTM

**Pull request merged**
